# Generated by Django 4.2.13 on 2024-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_hcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hcp',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
