# Generated by Django 4.2.13 on 2024-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_hcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hcp',
            field=models.FloatField(null=True),
        ),
    ]
